### ISSUE TITLE
cant fetch ubuntu ppa

### ISSUE THREAD

**Issue by stupied4ever** [nviennot/tmate#48]
Hit http://br.archive.ubuntu.com utopic-backports/universe i386 Packages                                                                                                                      
Hit http://br.archive.ubuntu.com utopic-backports/main Translation-en                                                                                                                         
Hit http://br.archive.ubuntu.com utopic-backports/universe Translation-en                                                                                                                     
Fetched 1.027 kB in 28s (35,8 kB/s)                                                                                                                                                           
W: Failed to fetch http://ppa.launchpad.net/nviennot/tmate/ubuntu/dists/utopic/main/binary-amd64/Packages  404  Not Found

W: Failed to fetch http://ppa.launchpad.net/nviennot/tmate/ubuntu/dists/utopic/main/binary-i386/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by shawneric** [comment]
Also having the same issue.

Ign http://mirrors.linode.com utopic InRelease
Ign http://mirrors.linode.com utopic-updates InRelease
Ign http://mirrors.linode.com utopic-backports InRelease
Hit http://mirrors.linode.com utopic Release.gpg
Hit http://mirrors.linode.com utopic-updates Release.gpg
Hit http://mirrors.linode.com utopic-backports Release.gpg
Hit http://mirrors.linode.com utopic Release
Hit http://mirrors.linode.com utopic-updates Release
Ign http://security.ubuntu.com utopic-security InRelease
Hit http://mirrors.linode.com utopic-backports Release
Hit http://security.ubuntu.com utopic-security Release.gpg
Hit http://security.ubuntu.com utopic-security Release
Hit http://mirrors.linode.com utopic/main Sources
Hit http://mirrors.linode.com utopic/restricted Sources
Hit http://mirrors.linode.com utopic/universe Sources
Hit http://mirrors.linode.com utopic/multiverse Sources
Hit http://mirrors.linode.com utopic/main amd64 Packages
Ign http://ppa.launchpad.net utopic InRelease
Hit http://mirrors.linode.com utopic/restricted amd64 Packages
Hit http://mirrors.linode.com utopic/universe amd64 Packages
Hit http://mirrors.linode.com utopic/multiverse amd64 Packages
Hit http://mirrors.linode.com utopic/main Translation-en
Hit http://mirrors.linode.com utopic-backports/restricted Sources
Hit http://mirrors.linode.com utopic-backports/multiverse Sources
Hit http://mirrors.linode.com utopic-backports/restricted amd64 Packages
Hit http://mirrors.linode.com utopic-backports/multiverse amd64 Packages
Hit http://mirrors.linode.com utopic-backports/multiverse Translation-en
Hit http://mirrors.linode.com utopic-backports/restricted Translation-en
Hit http://security.ubuntu.com utopic-security/main Sources
Hit http://security.ubuntu.com utopic-security/restricted Sources
Ign http://ppa.launchpad.net utopic InRelease
Hit http://mirrors.linode.com utopic/multiverse Translation-en
Hit http://mirrors.linode.com utopic/restricted Translation-en
Hit http://mirrors.linode.com utopic/universe Translation-en
Hit http://mirrors.linode.com utopic-updates/main Sources
Hit http://mirrors.linode.com utopic-updates/restricted Sources
Hit http://mirrors.linode.com utopic-updates/universe Sources
Hit http://mirrors.linode.com utopic-updates/multiverse Sources
Hit http://mirrors.linode.com utopic-updates/main amd64 Packages
Hit http://mirrors.linode.com utopic-updates/restricted amd64 Packages
Hit http://mirrors.linode.com utopic-updates/universe amd64 Packages
Hit http://mirrors.linode.com utopic-updates/multiverse amd64 Packages
Hit http://mirrors.linode.com utopic-updates/main Translation-en
Hit http://mirrors.linode.com utopic-updates/multiverse Translation-en
Hit http://mirrors.linode.com utopic-updates/restricted Translation-en
Hit http://mirrors.linode.com utopic-updates/universe Translation-en
Hit http://mirrors.linode.com utopic-backports/main Sources
Hit http://mirrors.linode.com utopic-backports/universe Sources
Hit http://security.ubuntu.com utopic-security/universe Sources
Hit http://security.ubuntu.com utopic-security/multiverse Sources
Hit http://security.ubuntu.com utopic-security/main amd64 Packages
Hit http://security.ubuntu.com utopic-security/restricted amd64 Packages
Hit http://mirrors.linode.com utopic-backports/main amd64 Packages
Hit http://mirrors.linode.com utopic-backports/universe amd64 Packages
Hit http://mirrors.linode.com utopic-backports/main Translation-en
Hit http://mirrors.linode.com utopic-backports/universe Translation-en
Hit http://security.ubuntu.com utopic-security/universe amd64 Packages
Hit http://security.ubuntu.com utopic-security/multiverse amd64 Packages
Hit http://security.ubuntu.com utopic-security/main Translation-en
Ign http://ppa.launchpad.net utopic InRelease
Hit http://security.ubuntu.com utopic-security/multiverse Translation-en
Hit http://security.ubuntu.com utopic-security/restricted Translation-en
Hit http://security.ubuntu.com utopic-security/universe Translation-en
Hit http://ppa.launchpad.net utopic Release.gpg
Ign http://ppa.launchpad.net utopic Release.gpg
Ign http://ppa.launchpad.net utopic Release.gpg
Hit http://ppa.launchpad.net utopic Release
Ign http://ppa.launchpad.net utopic Release
Ign http://ppa.launchpad.net utopic Release
Hit http://ppa.launchpad.net utopic/main amd64 Packages
Hit http://ppa.launchpad.net utopic/main Translation-en
Err http://ppa.launchpad.net utopic/main amd64 Packages
  404  Not Found
Ign http://ppa.launchpad.net utopic/main Translation-en_US
Ign http://ppa.launchpad.net utopic/main Translation-en
Err http://ppa.launchpad.net utopic/main amd64 Packages
  404  Not Found
Ign http://ppa.launchpad.net utopic/main Translation-en_US
Ign http://ppa.launchpad.net utopic/main Translation-en
W: Failed to fetch http://ppa.launchpad.net/jaywink/curldebian/ubuntu/dists/utopic/main/binary-amd64/Packages  404  Not Found

W: Failed to fetch http://ppa.launchpad.net/nviennot/tmate/ubuntu/dists/utopic/main/binary-amd64/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead.
ubuntulinodesvr@localhost:~$

**Comment by nviennot** [comment]
I'll take care of it tonight

**Comment by nviennot** [comment]
Done :)
