### ISSUE TITLE
Using local tmate server and if-shell in config, authentication fails

### ISSUE THREAD

**Issue by jtslear** [nviennot/tmate#50]
Good Morning,

I'm running our own tmate server and it works great (freakin' awesome actually).  However after fiddling with my `.tmux.conf` a certain config option prevents me from connecting to it.  The following config option was added to my dot files:
```
if-shell "[ -f ~/.tmux.conf.local ]" 'source ~/.tmux.conf.local'
```
During troubleshooting I've removed all the content except this one line from the config file as well as the tmux.conf.local and this appears to be the problematic item that prevents me from connecting to a locally run tmate server.

```
~ % tmate show-message
Fri Jan 30 08:52:33 2015 [tmate] Connecting to ...
Fri Jan 30 08:52:34 2015 [tmate] Cannot authenticate server
~ %
```
My tmate config:
```
set -g tmate-server-host "bld-tmate-01.redacted.com"
set -g tmate-server-port 22
set -g tmate-server-dsa-fingerprint "REDACTED"
set -g tmate-server-rsa-fingerprint "REDACTED"
set -g tmate-server-ecdsa-fingerprint "REDACTED"
```
And with the hopes of providing some log detail I ran `tmate -vv`, and those log files produced can be found here:
https://gist.github.com/jtslear/6c59587011f94b5e5170
https://gist.github.com/jtslear/80c0614f52987954a037

The odd thing I find about this is that tmate appears to be dropping the fact that I want to connect to a locally hosted server and reaches out to `master.tmate.io`.  I would assume the authentication then fails as I've got my servers' fingerprints in place rather than what the master.tmate.io servers fingerprints would be.

In troubleshooting I pulled the latest version of the tmate server from the repo master branch as of yesterday.  I'm running the latest version of tmate provided by brew of my workstation.
```
~ % brew list tmate
/usr/local/Cellar/tmate/1.8.10/bin/tmate
```

**Comment by nviennot** [comment]
Hi @jtslear :)

This is indeed a weird bug.

`if-shell` delays the configuration file processing, but tmate was started before the configuration files processing was done. I've pushed a commit so that tmate is started after the config files are fully loaded. Your issue should be gone :)

**Comment by nviennot** [comment]
(you can run `brew upgrade --HEAD tmate` to install with the patch in)

**Comment by jtslear** [comment]
Excellent!  Thank you sir.
