### ISSUE TITLE
Connection string doesn't make sense/garbage.

### ISSUE THREAD

**Issue by nnathan** [nviennot/tmate#51]
I installed my own tmate-server on  (RSA FP: de:c7:8c:5f:8d:d4:3f:fd:85:22:a8:2d:4f:dd:a1:fa ).

It gives me the connection string: `ssh -p2222 9LudoRikmm6q7uLULdeaTCWxH@3de1c99e1c30`

This doesn't make any sense whatsoever. On the server itself, I'm running the docker image from https://github.com/nicopace/tmate-docker.

I also don't see a persistent connection to the ssh server on the tmate server side (doing `netstat -anp`).

Any suggestions as to why this might not be working?

Thanks.

**Comment by nviennot** [comment]
I'm not familiar with this docker setup, but you need to pass a valid HOST variable as shown in the readme (`HOST=example.com` at the bottom). This is how you configure the host in the connection string (after the `@`). Looks like tmate is picking up the docker hostname, which is some random gibberish.

**Comment by nnathan** [comment]
Ah, that makes a lot of sense. I purposefully omitted it (ick). Thanks for that.

**Comment by nviennot** [comment]
happy pairing :+1:
