### ISSUE TITLE
tmate show-messages fails in Ubuntu

### ISSUE THREAD

**Issue by lobo-tuerto** [nviennot/tmate#52]
tmate show-messages fails in Ubuntu:

    tmate show-messages
    failed to connect to server

tmate alone works ok.

**Comment by nviennot** [comment]
`tmate show-messages` must be run within a tmate session.
(the `TMUX` env variable should be set)

**Comment by lobo-tuerto** [comment]
Oh, you are right. Thank you for the fast replies. :)

**Comment by nviennot** [comment]
I try :)
