### ISSUE TITLE
Restrict folder access

### ISSUE THREAD

**Issue by jvanbaarsen** [nviennot/tmate#54]
Is there a way to restrict a client to not go out of the folder that the tmate session was started in?

For example:

```shell
/home/Code/projectA/ $ tmate

# Working dir is now projectA

#Allow: cd subfolders
#Disallow cd ../
```

**Comment by nviennot** [comment]
No. You'd have to use tools like containers (e.g. docker) to do that.

**Comment by jvanbaarsen** [comment]
@nviennot Ok! Thanks!

**Comment by rudresh-dixit** [comment]
Can you please elaborate? Whelther to run a container before the connection, or some other way?
