### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [nviennot/tmate#57]
I would like to point out that identifiers like "[`__progname`](https://github.com/nviennot/tmate/blob/ed4020b5890cdccf930e82a61a8ce264404235fb/tmux.h#L41)" and "[`__tmate_status_message`](https://github.com/nviennot/tmate/blob/2f43ed93b7190839dfe890b97a168f766ca2376e/tmate.h#L150)" [do not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by nviennot** [comment]
`__progname` is in the tmux source code, so I won't touch it.

`__tmate_status_message` is not going to conflict with anything :)

btw, starting variables with `_` is totally fine. It's quite popular in the linux kernel for example: https://github.com/torvalds/linux/blob/master/arch/x86/include/asm/mutex_32.h#L24

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoid undefined behaviour?")?

**Comment by nviennot** [comment]
by your standards, the linux kernel depends on undefined behavior, and I trust the linux kernel. So I guess I'm okay with that :)

**Comment by elfring** [comment]
I would appreciate if source files of operating systems and corresponding applications will become [more standard-compliant](http://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797 "What are the rules about using an underscore in a C++ identifier?").

**Comment by nviennot** [comment]
being standard-compliant for the sake of being standard-compliant in not productive in my opinion.
what we want is to reduce the number of bugs in our applications. Renaming that variable will not give you that.

**Comment by elfring** [comment]
Can C standard-compliance help you to reduce the error probability around specific implementation details?

**Comment by nviennot** [comment]
For certain things yes, but for things like renaming a variable, no.

**Comment by elfring** [comment]
Is it so hard to delete a few underscores so that the affected source files do not need to tamper with the reserved name space more than it is absolutely required?

**Comment by nviennot** [comment]
C coding convention would tell you that a variable starting with `_` means it's private, or some subroutine of the non `_` version. It is often used in macros, to avoid conflicting with variables defined in the calling function (like `__ret` for example).

Adding `_` in front of variables is not just for shits and giggles. 1) It conveys information to the reader that this method is used by a wrapper hiding certain things (like acquiring a lock), or it should be used with caution 2) It avoid conflicts when exporting variables either from a macro, or globally.

I suggest you read a bit more of the linux kernel source code, one of the finest piece of C code, to understand C in its practicality.

**Comment by elfring** [comment]
There are coding styles which conflict with the standard specifications for the programming languages "C" and "C++".

You can continue to use also leading underscores in your identifiers if you care for consequences from reserved name space requirements.
