### ISSUE TITLE
Error connecting: kex error : no match for method server host key algo

### ISSUE THREAD

**Issue by hydro-b** [nviennot/tmate#59]
I installed a tmate-slave on a Ubuntu Vivid server (15.04). I try to connect from a Arch linux client with tmate 1.8.10. The client gives the following message:

[tmate] Error connecting: kex error : no match for method server host key algo: server [ssh-dss,ssh-rsa], client [ecdsa-sha2-nistp256]

The server reports the failed DH exchange.

tmate-slave log:

2015-08-21 17:28:22 [main] [tmate] Accepting connections on 2222
2015-08-21 17:28:30 [main] [tmate] Child spawned pid=6651, ip=213.136.12.151
2015-08-21 17:28:30 [.........................] [tmate] Exchanging DH keys
2015-08-21 17:28:30 [.........................] [tmate] FATAL Error doing the key exchange
2015-08-21 17:28:30 [main] [tmate] Child 6651 exited (255)

Strangely the client does not see / get the ecdsa key from the server. Is there a way to force a specific key exchange in tmate? I have checked that .tmate.conf has the correct fingerprints. I have both rsa and dsa keys in my ~/.ssh and a ssh-agent with loaded keys.

**Comment by nviennot** [comment]
I didn't put ECDSA support in the server: https://github.com/nviennot/tmate-slave/blob/master/tmate-ssh-server.c#L271-L275 because it would give me the warning of "oh no! the server's key has changed! someone is trying to MITM you" if I didn't update the server hosts as well, so I didn't do it, but feel free to add ECDSA support in the server, it should be two extra liness :)

**Comment by hydro-b** [comment]
On Fri, Aug 21, 2015 at 09:10:38AM -0700, Nicolas Viennot wrote:
> I didn't put ECDSA support in the server:
> https://github.com/nviennot/tmate-slave/blob/master/tmate-ssh-server.c#L271-L275
> because it would give me the warning of "oh no! the server's key has
> changed! someone is trying to MITM you" if I didn't update the server
> hosts as well, so I didn't do it, but feel free to add ECDSA support
> in the server, it should be two extra liness :)

That's what I did and it works now. Thanks for the quick reply!

Gr. Stefan

**Comment by RX14** [comment]
How may I force the tmux client not to use ecdsa to avoid this error?

**Comment by nviennot** [comment]
You mean the tmate client, or the ssh client that people use to join in?

**Comment by RX14** [comment]
The tmate client, this error shows when launching tmate for the host.

**Comment by nviennot** [comment]
I don't know how to disable ecdsa on the client. Add the ecdsa support in the server as I mentioned earlier :)

**Comment by RX14** [comment]
That seems particularly annoying, that the client ONLY negotiates ecdsa when the server doesn't support it, but I guess I will have to patch the server then.

I patched the server, now I get:
```
[tmate] Connecting to rx14.co.uk...
[tmate] Trying server 62.210.76.48
[tmate] [2] [ssh_connect] ssh_connect: libssh 0.6.0 (c) 2003-2014 Aris Adamantiadis, Andreas Schneider, and libssh contributors. Distributed under the LGPL, please refer to COPYING file for information about your rights, using threading threads_noop
[tmate] [2] [ssh_socket_connect] ssh_socket_connect: Nonblocking connection socket: 12
[tmate] [2] [ssh_connect] ssh_connect: Socket connecting, now waiting for the callbacks to work
[tmate] [1] [socket_callback_connected] socket_callback_connected: Socket connection callback: 1 (0)
[tmate] [1] [ssh_client_connection_callback] ssh_client_connection_callback: SSH server banner: SSH-2.0-tmate
[tmate] [1] [ssh_analyze_banner] ssh_analyze_banner: Analyzing banner: SSH-2.0-tmate
[tmate] [2] [ssh_packet_dh_reply] ssh_packet_dh_reply: Received SSH_KEXDH_REPLY
[tmate] [2] [ssh_client_curve25519_reply] ssh_client_curve25519_reply: SSH_MSG_NEWKEYS sent
[tmate] [2] [ssh_packet_newkeys] ssh_packet_newkeys: Received SSH_MSG_NEWKEYS
[tmate] [2] [ssh_packet_newkeys] ssh_packet_newkeys: Signature verified and valid
[tmate] Establishing connection to 62.210.76.48
[tmate] Cannot authenticate server
```
