### ISSUE TITLE
Detached but blocking?

### ISSUE THREAD

**Issue by vidstige** [nviennot/tmate#63]
I would like to have a script that repeatedly 

1. Spawns a tmate session
2. Sends the ssh command via a secure channel automatically
3. Waits for the tmate session to finish

Is there any way to do this smoothly? Tried with -d etc, but then waiting for the session to finish is messy.

**Comment by nviennot** [comment]
I've added a quick patch in the `wait-exit` branch.

Now you can do

```
tmate -S /tmp/tmate.sock new-session -d
tmate -S /tmp/tmate.sock wait session-exit
```

The event will be triggered as soon as the session exits. Not putting this in master as the API will most likely change.

Let me know if that works for you.

**Comment by vidstige** [comment]
Tanks for quick feedback! :) 

Sounds like it should do. I'd rather run master branch, but it's no hurry. When do you think it will be merged?

**Comment by nviennot** [comment]
Not sure. Test it out first :)

**Comment by vidstige** [comment]
Could not build it. Getting "curses not found" during `./configure`. I'm o ubuntu. Any nice apt package to recommend?

**Comment by nviennot** [comment]
follow the instruction on http://tmate.io -- from source tab.

**Comment by vidstige** [comment]
Worked like a charm. :-)

Another question. How will tmate handle no internet? If I change the `tmate-server-host` config to e.g. foobar, the tmate -d returns success, but then of course there is no ssh command returned by `tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}'`. Will it try to reconnect to tmate.io if the internet is down etc?

If not, is there a way to detect this and try to refresh the session periodically?

Yet another question. :) Previously I used the apt package. If I'm going to use this branch, what files needs to be packaged?

**Comment by nviennot** [comment]
tmate doesn't handle no internet that well:
1) it retries the connection to tmate servers forever (so that's good).
2) but after the initial connection, if there is a disconnection, the remote session blow up. There's no reconnection at this time. This is coming.

I'm not sure what needs to be packaged. I've been using https://github.com/nviennot/tmate-ppa to make the .deb and all.

**Comment by vidstige** [comment]
Alright, cool. Looks like you only need the `tmate` binary then. sweet.

**Comment by vidstige** [comment]
Thank you so much for all the help! :heart:

**Comment by nviennot** [comment]
my pleasure :)
